name: Build and Deploy to Sandbox

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Configure settings.xml
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>anypoint-exchange-v3</id>
                <username>${{ secrets.ANYPOINT_USERNAME }}</username>
                <password>${{ secrets.ANYPOINT_PASSWORD }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Build and stamp jar
        run: |
          mvn -B package --file pom.xml
          jar=$(ls target/*.jar | head -1)
          hash=$(git rev-parse --short "$GITHUB_SHA")
          mv "$jar" "$(dirname "$jar")/$(basename "$jar" .jar)-$hash.jar"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: target/*-$hash.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }} 

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: artifacts

      - name: List downloaded jars for debug
        run: ls -la artifacts      # valida que exista al menos un .jar :contentReference[oaicite:7]{index=7}

      - name: Deploy to CloudHub
        env:
          anypoint_username: ${{ secrets.ANYPOINT_USERNAME }}
          anypoint_password: ${{ secrets.ANYPOINT_PASSWORD }}
        run: |
          artifact=$(ls artifacts/*.jar | head -1)
          mvn -B deploy -DmuleDeploy \
              -Danypoint.username="$anypoint_username" \
              -Danypoint.password="$anypoint_password" \
              --file pom.xml
