name: Build and Deploy to Sandbox

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17  # Mule 4.9.x requiere Java 17

      - name: Generate Maven settings.xml
        uses: whelk-io/[email protected]
        with:
          # Credentials for Anypoint Exchange
          servers: >
            [{
              "id": "anypoint-exchange-v3",
              "username": "${{ secrets.anypoint_platform_username }}",
              "password": "${{ secrets.anypoint_platform_password }}"
            }]
          # Additional repositories for Everit JSON Schema and Maven Central
          repositories: >
            [
              {
                "id": "mulesoft-public",
                "name": "MuleSoft Public Repository",
                "url": "https://repository.mulesoft.org/nexus/content/repositories/public/"
              },
              {
                "id": "central",
                "name": "Maven Central",
                "url": "https://repo.maven.apache.org/maven2"
              }
            ]

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Stamp artifact file name with commit hash
        run: |
          artifact=$(ls target/*.jar | head -1)
          commitHash=$(git rev-parse --short "$GITHUB_SHA")
          mv "$artifact" "$(dirname "$artifact")/$(basename "$artifact" .jar)-$commitHash.jar"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: target/*.jar

      - name: Build for Exchange
        run: mvn -B -DskipTests package

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - uses: actions/download-artifact@v4
        with:
          name: artifacts

      - name: Deploy to CloudHub
        env:
          anypoint_username: ${{ secrets.anypoint_platform_username }}
          anypoint_password: ${{ secrets.anypoint_platform_password }}
        run: |
          artifact=$(ls artifacts/*.jar | head -1)
          # -DmuleDeploy activa la sección <cloudhub2Deployment> en el POM
          mvn -B deploy -DmuleDeploy \
              -Danypoint.username="$anypoint_username" \
              -Danypoint.password="$anypoint_password" \
              --file pom.xml
